-- 코드를 입력하세요
SELECT 
    R1.FOOD_TYPE,
    R1.REST_ID,
    R1.REST_NAME,
    R1.FAVORITES
FROM
    REST_INFO R1
JOIN
(SELECT
    FOOD_TYPE,
    MAX(FAVORITES) FAVORITES
FROM
    REST_INFO
GROUP BY 
    FOOD_TYPE) R2
ON
R1.FOOD_TYPE = R2.FOOD_TYPE
WHERE R1.FAVORITES = R2.FAVORITES
ORDER BY 1 DESC
    