#음식 종류별 즐겨찾기수 최댓값을 먼저구하고,
#해당하는 최댓값에 맞는 REST_ID,REST_NAME등을 끌어온다.
SELECT 
    R1.FOOD_TYPE,
    R1.REST_ID,
    R1.REST_NAME,
    R1.FAVORITES
FROM
    REST_INFO R1
JOIN
(SELECT
    FOOD_TYPE,
    MAX(FAVORITES) FAVORITES
FROM
    REST_INFO
GROUP BY 
    FOOD_TYPE) R2
ON
R1.FOOD_TYPE = R2.FOOD_TYPE
WHERE R1.FAVORITES = R2.FAVORITES
ORDER BY 1 DESC