SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    P.PRICE*T.TOTAL_AMOUNT TOTAL_SALES
FROM
    FOOD_PRODUCT P
JOIN
(SELECT
    PRODUCT_ID,
    SUM(AMOUNT) TOTAL_AMOUNT
FROM
    FOOD_ORDER
WHERE
    PRODUCE_DATE LIKE '2022-05%'
GROUP BY 1
) T
ON
    P.PRODUCT_ID = T.PRODUCT_ID
ORDER BY 3 DESC, 1