SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(O.AMOUNT)*P.PRICE TOTAL_PRICE
FROM
    FOOD_PRODUCT P
JOIN
    FOOD_ORDER O
ON
    P.PRODUCT_ID = O.PRODUCT_ID
WHERE
    PRODUCE_DATE LIKE '2022-05%'
GROUP BY
    1
ORDER BY
    3 DESC, 1