-- 코드를 입력하세요
SELECT
    F1.CATEGORY,
    F1.PRICE AS MAX_PRICE,
    F1.PRODUCT_NAME
FROM
    FOOD_PRODUCT F1
JOIN
(SELECT
    CATEGORY,
    MAX(PRICE) MAX_PRICE
FROM
    FOOD_PRODUCT 
GROUP BY 1) F2
ON
F1.CATEGORY = F2.CATEGORY
WHERE
    F1.PRICE = F2.MAX_PRICE
AND
    F1.CATEGORY IN ('과자','국','김치','식용유')
GROUP BY 1
ORDER BY 2 DESC
